<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Version>1.0.0</Version>
    <PackageId>Zed.EntityFrameworkCore</PackageId>
    <Title>Zed.EntityFrameworkCore</Title>
    <AssemblyTitle>Zed.EntityFrameworkCore</AssemblyTitle>
    <Description>Zed.EntityFrameworkCore is a library for Entity FrameworkC ore support</Description>
    <PackageReleaseNotes>Zed.EntityFrameworkCore is a library for Entity Framework Core support</PackageReleaseNotes>
    <Authors>ztepsic</Authors>
    <RequireLicenseAcceptance>false</RequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ztepsic/zed.entityframeworkcore</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ztepsic/zed.entityframeworkcore</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Zed EntityFrameworkCore</PackageTags>
    <Copyright>Copyright 2025</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Zed" />
  </ItemGroup>

</Project>
